- src/Property.php
- src/ValueObjectError.php
- src/ValueObjectException.php
- tests/TestClasses/OtherClass.php
- tests/ValueObjectTest.php
Although you tagged it with 'good first issue', I'll admit it wasn't easy :p There is probably a better way to solve this, but I'll submit the PR anyway, maybe get some good feedback. If I'm wasting your time; sorry, but just close it, no hard feelings.
Some issues I ran into: 
1. `ValueObjectException` should get a value of the class in the collection, not the array the class is in. But that would require changes for `set` in `Property`. I added an `is_array` check to `ValueObjectException` to avoid `array to string` issues , but there should be a better way to handle this.
2. `assertTypeEquals` in `Property` will recursively walk through the values of the array to check if the type matches. I feel like this should maybe be done in `isValidType`, but how combine this with the support for …
> Add generic collection support. Fixes #2

- src/Property.php
- src/ValueObject.php
- src/ValueObjectError.php
- tests/ValueObjectTest.php
Resolves #8.
Changed default value for `Property::$isNullable` to `true` to be consistent with test `empty_type_declaration_allows_everything`.
Added test to allow only explicitly specified nullable property.
> Throw exception on uninitialized non-nullable property.

- tests/DataTransferTransferObjectTest.php
- Using `assertContains` to check the specified message contains the expected string.
> Using assertContains to enhance assertions

- src/Property.php
- tests/DataTransferTransferObjectTest.php
PHP's `gettype()` returns "double" for float, causing an exception to be thrown for valid floats with something like:
> Invalid type: expected ExampleDto::floatVariable to be of type float, instead got value `5.1`.
Example class:
```php
class ExampleDto extends DataTransferObject
{
/** @var float */
public $floatVariable;
}
```
This change fixes the issue by providing a mapping from "double" to "float".
> Fix issue when requiring float in the DTO.

- CHANGELOG.md
- README.md
- src/Arr.php
- src/Property.php
- tests/DataTransferTransferObjectTest.php
- tests/TestClasses/NestedParentOfMany.php
This resolves #44.
This commit adds support for automatically casting of arrays to arrays of DTOs. Example from the update README:
```php
class TagData extends DataTransferObject
{
/** @var string */
public $name;
}
class PostData extends DataTransferObject
{
/** @var \TagData[] */
public $tags;
}
```
`PostData` will automatically construct tags like such:
```php
$postData = new PostData([
'tags' => [
['name' => 'foo'],
['name' => 'bar']
]
]);
```
> Adds automatic casting of DTO arrays.

- CHANGELOG.md
- src/Property.php
- tests/DataTransferTransferObjectTest.php
- tests/TestClasses/EmptyChild.php
This adds a new `EmptyChild` DTO test class and associated test to resolve #47. Empty DTO's can be cast to using an empty array now.
> Fixes #47 - Allowing empty DTO's to be cast via empty arrays

- CHANGELOG.md
- README.md
- src/DataTransferObject.php
- src/DataTransferObjectError.php
- src/ImmutableDataTransferObject.php
- tests/ImmutableTest.php
By using `ImmutableDataTransferObject` as a proxy, we're able to have the best of both worlds!
closes #12
> Immutable data transfer objects

- README.md
From https://writingexplained.org/cast-vs-casted:
> Casted is an incorrect past tense conjugation of the verb cast. It almost never appears in print or edited works of any kind.
Example of past tense from https://laravel.com/docs/6.x/eloquent-mutators#attribute-casting:
> Now the `is_admin` attribute will always be **cast** to a boolean when you access it...
> Changed casted to cast in readme

- README.md
- src/Property.php
- tests/DataTransferObjectTest.php
This PR aims to support iterable types. see #70 
It can be used with simple iterable type : 
```php
/** @var iterable */
public $items
```
but also with types
```php
/** @var iterable<string> */
public $strings
```
or with DTOs
```php
/** @var iterable<\App\DTO\NestedDto> */
public $nested
```
I would be happy to push further or add extra tests if needed
> Support for iterable type

- src/DataTransferObject.php
- tests/DataTransferObjectTest.php
I've a project where I need to use a public static property on a DTO but
it clashes because the code doesn't ignore it. But it should, as they're
not relevant for the data encapsulation of the DTO.
> [DTO] Ignore static public properties

- src/DataTransferObject.php
My previous PR https://github.com/spatie/data-transfer-object/pull/76 wasn't deemed in the scope of the library => fair point 👍 
Still I would like the ability to use the feature outlined in the PR in my own project.
As it stands right now, I've to override the whole constructor, slightly adjust it and make a copy of `getFieldValidators`.
With these changes, I'm able to simple override these methods and provide my own logic:
- allow returning my own ValueCaster instead of hardcoding `new ValueCaster` in the constructor
- ability to control the casting by overriding `castValue`
- change visibility of `getFieldValidators` from private to protected
Otherwise someone who might want to use a custom constructor couldn't use the cache "as is"
Thanks!
> Improve extendability of DataTransferObject

- src/DataTransferObjectError.php
- tests/DataTransferObjectTest.php
- tests/ImmutableTest.php
I believe this is an error and wasn't caught so far because no tests for the actual message did exist.
In `\Spatie\DataTransferObject\DataTransferObjectError::invalidType` this code was executed:
```php
$currentType = gettype($value);
```
but it was done so _after_ `$value` was possible overwritten like this:
```php
if ($value === null) {
$value = 'null';
}
if (is_object($value)) {
$value = get_class($value);
}
if (is_array($value)) {
$value = 'array';
}
```
Which basically made `gettype($value);` to yield `string` in the majority of cases.
This PR fixes this.
Please also see the 2nd commit stand-alone, showing the change form the old to the new message  => https://github.com/spatie/data-transfer-object/commit/182c9251e5fb78e6a7c53d5c7f48a72a5537017e
> DataTransferObjectError::invalidType : get actual type before mutating $value for the error message

- src/DataTransferObject.php
- tests/DataTransferObjectTest.php
The previous fix in https://github.com/spatie/data-transfer-object/commit/66618c96c88f83a9e6c19eb2a0c8868ea18974d9 didn't
consider serialization where we also need to skip it 🤷‍♀️
~Batteries~ test included!
> [DTO] Ignore static properties also when serializing

- README.md
Since [json2dto](https://github.com/atymic/json2dto) now has a CLI I thought it would be worth mentioning that in the description :)
Both the CLI and GUI support nested DTOs as well now, so added that to the description as well.
Thanks!
> docs: update json2dto readme description

- README.md
- I introduced arrayOf some time ago and it turns out, it's perfect with for the collection
- `@method` can be used, IDEs (PhpStorm) can still properly autocomplete this.
Since the `Collection` is supposed to be a small enhancement for type safety, I thought making it less boiler-platey might be welcome
> readme: update collection examples

- src/PropertyFieldValidator.php
- tests/PropertyFieldValidatorTest.php
The reflection types don't seem to be being passed to the TypeMapping which leads to wrong results in the validator because it uses `gettype` which has a different result than the reflection types.
> Fix: Validator for typed 7.4 properties

- .github/workflows/phpstan-extension.yml
- CHANGELOG.md
- README.md
- composer.json
- src/PHPstan/PropertiesAreAlwaysInitializedExtension.php
- tests/PHPStan/ExampleDTO.php
- tests/PHPStan/phpstan-with-extension.neon
- tests/PHPStan/phpstan-without-extension.neon
Please read the discussion in https://github.com/spatie/data-transfer-object/issues/129 first.
I decided to go ahead and suggest a simple inclusion of the PHPStan extension for now instead of separate repo to avoid the overhead of managing a dedicate package for a few lines of code.
The idea is:
- the extension installed
- phpstan is suggested for composer
- end users can enable the extension manually with this neon configuration
```neon
services:
-
class: Spatie\DataTransferObject\PHPstan\PropertiesAreAlwaysInitializedExtension
tags:
- phpstan.properties.readWriteExtension
```
Tests are added with a dedicated workflow:
- installs phpstan (just the latest version for now)
- runs a positive and a negative test, i.e. ensures that activating/absence of the extension works correctly.
Ad …
> Add extension for PHPStan to support checkUninitializedProperties

- README.md
Closes #148 by adding a reference to the Data Transfer Object Factory package in the external tools section.
> Adds Data Transfer Object Factory to the README

- src/FieldValidator.php
Return type should be an array (with data or empty) and not null.
See https://github.com/spatie/data-transfer-object/issues/163
> Fix incorrect return type

- src/DataTransferObjectCollection.php
- tests/DataTransferObjectCollectionTest.php
With the introduction of 2.8.0 (https://github.com/spatie/data-transfer-object/commit/88ffe870053853cb086d95a3549082e8b97e7cba) the `DataTransferObjectCollection` iterates over copy of the internal `$collection` array instead of over the current value of array itself.
This breaks backwards compatibility as demonstrated by the testcase below. Before 2.8.0, this test would pass and on 2.8.0 it fails.
```php
public function test_it_iterates_over_internal_array(): void
{
$list = new class() extends DataTransferObjectCollection {
};
$list[] = new TestDataTransferObject(['testProperty' => 1]);
$list[] = new TestDataTransferObject(['testProperty' => 2]);
$list[] = new TestDataTransferObject(['testProperty' => 3]);
$traversed = [];
foreach ($list as $id => $item) {
$traversed[$id] = …
```
> Prevent DataTransferObjectCollection from iterating over array copy

- src/Reflection/DataTransferObjectProperty.php
- tests/DataTransferObjectTest.php
- tests/Dummy/ComplexDtoWithNullableProperty.php
Currently, a DTO like 
```php
class ComplexDtoWithNullableProperty extends DataTransferObject
{
public string $name;
public ?BasicDto $other;
}
```
cannot be created with
```php
new ComplexDtoWithNullableProperty(name: 'a', other: null)
```
because we are having a
```
TypeError: Only arrays and Traversables can be unpacked
vendor/spatie/data-transfer-object/src/Casters/DataTransferObjectCaster.php:17
vendor/spatie/data-transfer-object/src/Reflection/DataTransferObjectProperty.php:41
```
This PR fixes the issue applying the cast only when given value is not null.
> Fix cast with null

- src/Casters/DataTransferObjectCaster.php
- tests/DataTransferObjectTest.php
It is sometimes convenient to give an already created nested DTO to the parent DTO.
For example, if you want to map an api response which looks like 
```json
{  
"product": "the product",
"value": {
"cents": 100,
"sign": "€"      
}
}
```
to
```php
class Product extends DataTransferObject {
public string $label;
public string $price;
public static function fromApi(array $api) 
{
return new self([
'label' => $api['product'], 
'price' => Price::fromApi($api['value'])
]);
}
}
class Price extends DataTransferObject {
public int $amount;
public string $currency;
public static function fromApi(array $api) 
{
return new self([
'amount' => $api['cents'],
'currency' => $api['sign']
]);
}
}
```
It is currently not possible as DataTransferObject will try to cast it as well.
~~This fix may be …
> Give dto to caster

- composer.json
As the code is filled with JetBrains helper attributes like `#[Immutable]` now, it's best to include the package in `require-dev`. This will solve issues with other IDE's and self-sufficient.
https://packagist.org/packages/jetbrains/phpstorm-attributes
https://github.com/JetBrains/phpstorm-attributes
> Add jetbrains attributes package

- src/Reflection/DataTransferObjectProperty.php
- tests/UnionDtoTest.php
Right now properties with a union type are not supported because the `resolveCasterFromType` method in `DataTransferObjectProperty` class throw an exception in the `$type->getName()` call (The `getName` method does not exists in `ReflectionUnionType`.
I don't know if the solution I implemented is the best solution but in my tests it works.
> Fix union type casting

- src/Reflection/DataTransferObjectProperty.php
- tests/DefaultCasterTest.php
Calling `getAttributes` on a class returns only attributes applied to that class and not those applied to the parent classes, so we need to cycle through the entire hierarchy to load default casts from parent classes.
> Resolve default cast from parent classes

- README.md
- src/Attributes/CastWith.php
- src/Reflection/DataTransferObjectProperty.php
- tests/CustomCasterArgumentsTest.php
Custom arguments can be used to provide metadata and extra context for
the user-defined casters.
This can be used, for example, to create generic array casters.
Fixes #193
> Add custom arguments to the CastWith attribute

- CHANGELOG.md
- README.md
- src/Casters/ArrayCaster.php
- tests/CustomCasterArgumentsTest.php
This PR adds the ability to cast objects that implement `ArrayAccess` to the `ArrayCaster`, it also adds the appropriate testing to ensure this works.
It should also be noted, I narrowed down the exception type to `LogicException` as opposed to `Exception` when casting an object other than an array or `ArrayAccess` is attempted.
> Adds ArrayAccess casting to the ArrayCaster.

- src/Attributes/CastWith.php
Why class name?
https://www.php.net/manual/en/function.class-implements.php
The second parameter is boolean. I understand that there will be a cast, but still.
> Set boolean to class_implements

- src/Exceptions/ValidationException.php
Hello! Just started using the library, and we're really enjoying it.
One use case that isn't easily supported (as far as I can see) is being able to access the results of a ValidationException – at present they are concatenated into a string.
This doesn't really work for our use case as we need to access individual messages and perform post-processing on the exceptions.
There's a number of ways that this could be done, but I thought the least invasive would be making the validationErrors available as a property (dataTransferObject has been promoted more for completeness).
> Promoted dataTransferObject and validationErrors

- README.md
- src/Casters/ArrayCaster.php
- tests/CustomCasterArgumentsTest.php
Hi Brendt and co.  Thanks for your work on this useful project.
I came across a situation that would be helpful to me if it were altered slightly.  I hope it's something that's helpful for others too…
---
Usually,  I build DTO objects by passing the desired child DTO objects.  But sometimes I need these _same_ DTOs to be hydrated from serialised arrays.
When using the **ArrayCaster** to cast arrays into objects,  the elements to be cast _must_ be arrays (otherwise an error is generated).
This PR lets you also pass in objects of the desired type (no cast needed),  as well as the original behaviour (which casts the array).  This way, both situations are covered.
``` php
class Bar extends DataTransferObject
{
/** @var Foo[] */
public array $collectionOfFoo;
}
class Baz extends …
```
> Update ArrayCaster to accept objects (of the correct class) alongside arrays that get cast like normal

- .gitignore
- README.md
- src/Casters/ArrayCaster.php
- src/Casters/DataTransferObjectCaster.php
- src/Reflection/DataTransferObjectProperty.php
- tests/Dummy/RoundingCaster.php
- tests/UnionDtoTest.php
> Support union type in casters

- README.md
- src/Arr.php
- src/Attributes/MapFrom.php
- src/DataTransferObject.php
- src/Reflection/DataTransferObjectProperty.php
- tests/MapFromTest.php
This pull request adds the ability to map DTO properties from source properties with different names.
This approach goes against the philosophy of doing a `1:1` mapping of DTOs, but it is undoubtedly helpful in the several cases that I present below.
```php 
class EventDTO extends DataTransferObject
{
#[MapFrom('nbParticipants')]
public string $participantCount;
}
$dto = new EventDTO([
'nbParticipants' => 6,
]);
```
```php 
class ProfileDTO extends DataTransferObject
{
public string $name;
#[MapFrom('address.city')]
public string $city;
}
$dto = new ProfileDTO([
'name' => 'John Doe',
'address' => [
'city' => 'London',
]
]);
```
```php 
class UserDTO extends DataTransferObject
{
#[MapFrom(0)]
public string $firstName;
#[MapFrom(1)]
public string $lastName;
}
$dto = new UserDTO(['John', …
```
> Support mapped properties

- src/DataTransferObject.php
- tests/DataTransferObjectTest.php
- tests/Dummy/ComplexStrictDto.php
I came across an issue where the result of the custom `Spatie\DataTransferObject\Arr` helper is not used, which results in an exception with Strict DTO's. 
The custom `Spatie\DataTransferObject\Arr` helper is different from the Laravel `Arr` helper in that it returns an array instead of modifying an array passed by reference. 
This bug was introduced in 3.6.0.
> Fix array assignment bug with strict dto's

- src/Arr.php
- tests/MapFromTest.php
An alternative solution to #230 without using references.
Fixes #229
> Correct behavior of Arr::forget with dot keys

- src/Reflection/DataTransferObjectProperty.php
- tests/DataTransferObjectTest.php
- tests/Dummy/ComplexDtoWithParent.php
- tests/Dummy/ComplexDtoWithSelf.php
This PR fixes a bug when a type property has the `self` or `parent` keyword.
Here is a simple example with a nullable self property:
```php
class MyDTO extends DataTransferObject
{
public string $name;
public ?self $parent;
}
$dto = new MyDTO([
'name' => 'a',
'parent' => ['name' => 'b'],
]);
// TypeError: Cannot assign array to property MyDTO::$parent of type ?self
// vendor/spatie/data-transfer-object/src/Reflection/DataTransferObjectProperty.php:47
// vendor/spatie/data-transfer-object/src/DataTransferObject.php:29
```
The same applies for the `parent` keyword.
The reason is that the `DataTransferObjectProperty` cannot resolve the caster (e.g. `DataTransferObjectCaster`) for the property, because `resolveCasterFromType()` returns an empty array.
This happens because `$type->getName()` …
> Cast properties with `self` or `parent` type

- .github/workflows/test.yml
- src/DataTransferObjectCollection.php
This should reduce all the deprecation warnings on PHP 8.1
> V2 deprecation warnings

- composer.json
- src/Casters/EnumCaster.php
- tests/Casters/ArrayCasterTest.php
- tests/Casters/EnumCasterTest.php
- tests/Stubs/IntegerEnum.php
- tests/Stubs/SimpleEnum.php
- tests/Stubs/StringEnum.php
Hi there!
Me and my team often use enum caster, in our DTOs and it would be gr8 to have it by default in package
The only problem that I faced - I can't cover this caster with tests inside the package, cuz package supports PHP 8.0, and enums comes since 8.1
Here is usage example:
P.S. I will also add this information in readme, if you accept this PR
> Added enum caster

- src/Casters/EnumCaster.php
- tests/Casters/EnumCasterTest.php
This PR allows to cast enums, not just enum values.
> allow enum casting not only enum value casting

- tests/MapFromTest.php
This is pull request adding **failing test** as requested -> https://github.com/spatie/data-transfer-object/issues/298
Currently `dto_can_have_numeric_keys` passes but `dto_can_have_numeric_keys_in_nested_dto` fails.
> Add test for "Cannot use positional argument after named argument during unpacking" error

- src/Casters/DataTransferObjectCaster.php
- tests/MapFromTest.php
This pull request fixes a bug that causes properties mapped from a positional argument to fail after the argument array is unpacked into the casted child DTO. This fixes #298.
> Fix positional after named
